### ISSUE TITLE
How do you run all test262 tests at once?

### ISSUE THREAD

**Issue by evilpie** [bterlson/test262-harness#54]
Specifying something like `test262/test/**/**.js` only runs test two sub-directories deep, but I want to run _all_ tests. I can't figure how to do that.

**Comment by leobalter** [comment]
the current example from the README is misleading. If you're running it from a *nix system, you need to wrap the path in single quotes so you can get Glob to work for you, otherwise you'll have an undesirable path expansion.

- `test262-harness 'test262\test\**\*.js' --hostType node --hostPath <path to node.exe>`

**Comment by evilpie** [comment]
Oh wow, I should have realized that. Maybe the shell could output the pattern again, so you actually see the difference?

**Comment by leobalter** [comment]
this is easy to do, but it is probably better with some specific reporter/output. The idea for this tool is also to produce a consumable output, like a tap report or json format.

**Comment by bterlson** [comment]
I'm so frustrated with this. I wish there were a good cross-platform way to uniformly handle glob patterns without quotes :(

**Comment by leobalter** [comment]
Tell me about it.

**Comment by thorn0** [comment]
Why not have default values for the glob, `hostType` and `hostPath`?

**Comment by bterlson** [comment]
thorn0: a default for the glob (to run all tests) seems good, but what would you default "hostType" and "hostPath" to?

**Comment by thorn0** [comment]
The current Node executable used to launch the harness.
